#ifndef __RunNumberHeader__
#define __RunNumberHeader__


	/*
		Automated generated by Yige HUANG's python script.
		Generated time: Thu Mar 28 17:03:48 2024
	*/


#include <map>


namespace RunNumber {

	static const std::map<Int_t, Int_t> mRunIdxMap = {
		{	123,	    0},
		{	234,	    1},
		{	345,	    2},
		{	456,	    3},
		{	999,	    4},
	};
}


#endif
